[profile.default]
src = 'contracts'
out = 'artifacts/foundry'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache/foundry'
solc_version = '0.8.19'
optimizer = true 
optimizer_runs = 200
# We need "via_ir" for testing to workaround the stack too deep issue 
# "via_ir" is cool but it will slow down the compilation.
# So We disable most of the optimization steps to make the compilation faster. 
# see more at here: https://github.com/ethereum/solidity/issues/12533
via_ir = true
[profile.default.optimizer_details]
peephole = false
inliner = false
jumpdestRemover = false
orderLiterals = false
deduplicate = false
cse = false
constantOptimizer = false
yul = true
# The camel case may be changed to snake in the future 
# https://github.com/foundry-rs/foundry/issues/5175 
[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ""

[fuzz]
runs = 256